#!/usr/bin/env bash

# This script scales the Django app deployment to 3 replicas
# and monitors resource usage.

DEPLOYMENT_NAME="messaging-app-deployment"
REPLICAS=3

echo "Scaling deployment '$DEPLOYMENT_NAME' to $REPLICAS replicas..."
kubectl scale deployment "$DEPLOYMENT_NAME" --replicas="$REPLICAS"

echo -e "\nVerifying that $REPLICAS pods are running..."
# Wait for pods to become ready
kubectl rollout status deployment "$DEPLOYMENT_NAME"

echo -e "\nListing all pods for deployment '$DEPLOYMENT_NAME':"
kubectl get pods -l app=messaging-app

echo -e "\nLoad testing with 'wrk' (optional - please install wrk first)..."
echo "Example: wrk -t2 -c50 -d30s --latency http://<YOUR_INGRESS_URL>/api/"

echo -e "\nMonitoring resource usage of pods (requires 'metrics-server' to be running):"
# To install metrics-server in Minikube, run: minikube addons enable metrics-server
kubectl top pods -l app=messaging-app

echo -e "\nMonitoring resource usage of nodes:"
kubectl top nodes
