# Generated by Django 5.2.4 on 2025-08-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_remove_message_edited_message_edited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
