version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: messaging_db_container
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: messaging_web_container
    # Use the wait-for-db.sh script as the entrypoint
    entrypoint: ["wait-for-db.sh", "db"]
    # The actual command to run after the database is ready
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  db_data: