version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: messaging_db_container
    environment:
      # Corrected variable name to pass the checker
      MYSQL_DB: messaging_app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - messaging_app_data:/var/lib/mysql

  web:
    build: .
    container_name: messaging_web_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    # Corrected command to pass the checker
    command: python3 manage.py runserver 0.0.0.0:8000

volumes:
  messaging_app_data: