// messaging_app/Jenkinsfile
pipeline {
    agent any
    environment {
        DOCKER_HUB_USERNAME = 'geonjogu23' 
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo 'Checking out source code...'
                // Corrected branch name from 'main' to 'master'
                git branch: 'master', credentialsId: 'github-credentials', url: 'https://github.com/Geoffy1/alx-backend-python.git'
            }
        }
        stage('Run Tests') {
            steps {
                echo 'Installing dependencies and running tests...'
                sh '''
                    sudo apt-get update
                    sudo apt-get install -y python3 python3-pip python3-venv
                    
                    cd messaging_app
                    python3 -m venv venv
                    source venv/bin/activate
                    pip install -r requirements.txt
                    pytest
                '''
            }
        }
        stage('Build and Push Docker Image') {
            steps {
                echo 'Building and pushing Docker image...'
                script {
                    sh 'cd messaging_app'
                    sh "docker build -t ${env.DOCKER_HUB_USERNAME}/messaging-app:latest ."
                    
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh "docker login -u ${env.DOCKER_USERNAME} -p ${env.DOCKER_PASSWORD}"
                        sh "docker push ${env.DOCKER_HUB_USERNAME}/messaging-app:latest"
                    }
                }
            }
        }
    }
}